### ISSUE TITLE
Ordner Metadaten nicht mehr vorhanden

### ISSUE THREAD

**Issue by dlippold** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland#10]
Den Ordner mit den Metadaten (https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland/blob/main/Metadaten/) und insbesondere die darin enthaltene Datei `zenodo.json` gibt es nicht mehr (vermutlich seit 14.10.). Ich hoffe, das soll nicht so sein. Auf der Hauptseite wird im Abschnitt "Metadaten" zumindest noch darauf verwiesen.

Bitte den Ordner mit Inhalt möglichst wieder herstellen.

**Comment by HannesWuensche** [comment]
Liebe User,

Teil unseres Veröffentlichungsprozesses ist die Publikation der Daten auf Zenodo.org. Zenodo hat am Freitag eine Systemupdate vorgenommen und in diesem Zuge auch sein API angepasst.

In der [Dokumentation](https://help.zenodo.org/docs/about/whats-changed/) war diese Änderung nicht aufgeführt, sodass wir vorab nicht davon ausgegangen sind, Anpassungen in unserem Prozess vornehmem zu müssen. Leider kam es am Wochenende dann zu einem Ausfall unseres Prozesses, da die Zenodo API sich nicht wie gewohnt verhalten hat.

Wir nehmen derzeit die Anpassung bzw. warten auf einen stabilen Service durch Zenodo. Bis dahin stellen wir die Daten weiter auf Github bereit, jedoch ohne die Metadaten und ohne Updates der DOI in den Dokumentationen. Die fehlenden Zenodo-Versionen werden nachgereicht und die Commits entsprechend angepasst.

Beste Grüße
@HannesWuensche
für das Team RKI | Open Data

**Comment by HannesWuensche** [comment]
Lieber User,

In einer ersten Schritt sind jetzt die Metadaten wieder aktuell und verfügbar. 
Die Aktualisierungen auf Zenodo stehen leider nach wie vor nicht zur Verfügung, da Zenodo Probleme mit seiner API hat. 

Wir sind weiter dran und versuchen schnellst möglich wieder in Normalbetrieb überzugehen. 

Beste Grüße
@HannesWuensche
für das Team RKI | Open Data
