### ISSUE TITLE
2023-10-27 Kompletter Ausfall?

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland#11]
Wird heute noch nachgeliefert? Oder ist ein größeres Problem?

Jan

**Comment by RKIOpenData** [comment]
Hallo @jwildeboer,

die Daten kamen heute leider verspätet, sind aber jetzt da.

viele Grüße
Knut Perseke
für das Team RKI | Open Data
