### ISSUE TITLE
09.01.2024

### ISSUE THREAD

**Issue by dieter754** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland#13]
Die Datei ist leer!

**Comment by Rubber1Duck** [comment]
Moin, na ja leer ist die Datei nicht gerade, jedoch sind alle Einträge "genullt" worden. vieleicht das Ende der Berichterstattung?!?

**Comment by Rubber1Duck** [comment]
> Das heutige File in der Auswertung. Das ist ein Data Rollback der gesamten Pandemie. Deswegen die Frage, ob das so sein soll oder ob sich da ein Fehler eingeschlichen haben könnte.
> 
> Mit dem Jahreswechsel laufen auch immer gerne Licensen oder Certificates ab.
> 
> Anzahl Fälle : -38780921 Anzahl Fälle A00-A04 : -1038990 Anzahl Fälle A05-A14 : -4501057 Anzahl Fälle A15-A34 : -11220010 Anzahl Fälle A35-A59 : -15047352 Anzahl Fälle A60-A79 : -5210137 Anzahl Fälle A80+ : -1731534 Anzahl Fälle unbekannt : -31841 Anzahl Todesfälle : -180578 Anzahl Todesfälle aktuell : Anzahl Todesfälle korrektur : -180578 Anzahl Todesfälle A00-A04 : -56 Anzahl Todesfälle A05-A14 : -42 Anzahl Todesfälle A15-A34 : -494 Anzahl Todesfälle A35-A59 : -8647 Anzahl Todesfälle A60-A79 : -54029 Anzahl Todesfälle A80+ : -117296 Anzahl Todesfälle unbek. : -14 Inzidenz Datenstand : 18.3 Inzidenz Meldedatum : 0

genau das meinte ich mit "genullt" ......

**Comment by Soran56** [comment]
Deswegen habe ich es versucht zu präzisieren. Damit sich Fehler schneller finden. 
Einen solchen Fehler gab es es bisher in dieser Form noch nicht.

**Comment by Rubber1Duck** [comment]
da gebe ich dir recht, das gab es in dieser Form noch nicht.
und "Absicht" macht in meinen Augen auch keinen Sinn, warum sollte mann den gesamten Verlauf löschen wollen!?
Okay warten wir mal eine Reaktion ab ................

**Comment by MaHi84** [comment]
@HannesWuensche habt ihr nähere Infos für uns?

**Comment by MaHi84** [comment]
Das Repository [COVID-19_7-Tage-Inzidenz_in_Deutschland](https://github.com/robert-koch-institut/COVID-19_7-Tage-Inzidenz_in_Deutschland) wurde vor zwei Stunden (anhand der aktuellen Falldaten) aktualisiert. Scheint sich also im Hintergrund was zu tun. 😄

**Comment by RKIOpenData** [comment]
Liebe User,

die technischen Probleme bei der Generierung der Infektionsdaten sind jetzt erstmal behoben und wir können die aktuellen 
Zahlen wieder veröffentlichen (ab morgen dann hoffentlich auch wieder im Laufe des Vormittags).
Ich lasse das Issue trotzdem erstmal noch auf. Falls es in den nächsten Tagen noch Anmerkungen zu den Daten gibt kann hier gern kommentiert werden.

Beste Grüße
Knut Perseke
für das Team RKI | Open Data

**Comment by Rubber1Duck** [comment]
Hallo Herr Perske,
wann wird das Archiv Repo aktualisiert? Und wird es aktualisierte Daten für den 9.1.2023 im Archiv geben?
MfG
Peter Markewitz

**Comment by Soran56** [comment]
Hallo, 

Von der Ergebnissen, passt das aktuelle File. Allerdings ist die Inzidenzberechnung, mit dem gestrigen, fehlerhaften File für die Füße. (-46600). Um eine weiterhin kontinuirerliche Reihe zu erhalten, sollte das Fehlerhafte File vom 09-01-2024, gegen das richtige File ausgetauscht werden. Entwerder hier unter dem Tag 2024-01-09 und / oder unter dem Archiv in https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv.

Resultate aus dem Datafile vom 10-JAN-2024.
Anzahl Fälle                 : 2102
Anzahl Fälle A00-A04         : 98
Anzahl Fälle A05-A14         : 20
Anzahl Fälle A15-A34         : 201
Anzahl Fälle A35-A59         : 392
Anzahl Fälle A60-A79         : 703
Anzahl Fälle A80+            : 685
Anzahl Fälle unbekannt       : 3
Anzahl Todesfälle            : 132
Anzahl Todesfälle aktuell    : 134
Anzahl Todesfälle korrektur  : -2
Anzahl Todesfälle A00-A04    : 2
Anzahl Todesfälle A05-A14    : 
Anzahl Todesfälle A15-A34    : -1
Anzahl Todesfälle A35-A59    : 5
Anzahl Todesfälle A60-A79    : 42
Anzahl Todesfälle A80+       : 84
Anzahl Todesfälle unbek.     : 
Inzidenz Datenstand          : -46559.3
Inzidenz Meldedatum          : 2.4

**Comment by RKIOpenData** [comment]
Hallo @Rubber1Duck und @Soran56,

wir haben jetzt die Aktualisierung des Archivs vorgenommen und das upgedatete File vom 09.01. eingefügt.

Beste Grüße
Knut Perseke
für das Team RKI | Open Data

**Comment by Soran56** [comment]
Ja, das passt. Vielen  Dank.

Datenstand                   : 09.01.2024
Anzahl Fälle                 : 3573
Anzahl Fälle A00-A04         : 182
Anzahl Fälle A05-A14         : 44
Anzahl Fälle A15-A34         : 285
Anzahl Fälle A35-A59         : 689
Anzahl Fälle A60-A79         : 1140
Anzahl Fälle A80+            : 1232
Anzahl Fälle unbekannt       : 1
Anzahl Todesfälle            : 79
Anzahl Todesfälle aktuell    : 82
Anzahl Todesfälle korrektur  : -3
Anzahl Todesfälle A00-A04    : 
Anzahl Todesfälle A05-A14    : 
Anzahl Todesfälle A15-A34    : 
Anzahl Todesfälle A35-A59    : 1
Anzahl Todesfälle A60-A79    : 32
Anzahl Todesfälle A80+       : 46
Anzahl Todesfälle unbek.     : 
Inzidenz Datenstand          : 20.3
Inzidenz Meldedatum          : 20.3
