### ISSUE TITLE
Kein Datenupdate am 11.02.2024

### ISSUE THREAD

**Issue by Soran56** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland#15]
Das Datenupdate am 11.02.2024 hat nicht funktioniert.

**Comment by Rubber1Duck** [comment]
im Archiv Repo gibt es einen Commit am 11.02.2024 und einen tag 2024-02-11 wo allerdings das File 2024-02-10_Deutschland_SarsCov2_Infektionen.csv.xz hinzugefügt wurde!
Einen commit am 10.02.2024 und eine tag 2024-02-10 gibt es nicht!
Irgendwie läuft das hier ziemlich schief .....
Da hier mitlerweile die Daten vom 12.02.2024 commited wurden fehlen also die Daten vom 11.02.2024! sowohl hier in der Historie, als auch im Archiv repo!
wird das noch gerade gezogen?

**Comment by HannesWuensche** [comment]
Liebe Alle,

wir haben die Daten soeben im Archiv nachgetragen (Siehe [#34](https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv/issues/34))
In der commit history werden sie jedoch nicht nachgezogen.  

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data
