### ISSUE TITLE
Vorkomprimierte Version von `Aktuell_Deutschland_SarsCov2_Infektionen.csv`

### ISSUE THREAD

**Issue by yetzt** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland#2]
Eine mit `gzip`, `xz` oder `brotli` vorkomprimierte CSV-Datei wäre deutlich kleiner und würde einige der Probleme mit großen Dateien im Repository für die Gegenwart lösen.

* `gzip -9` → ~24MB
* `xz -z9` →  ~16MB
* `brotli -11` → ~19MB

**Comment by rgerhards** [comment]
Aus git Sicht sind die Deltas wesentlich kleiner.

Was sich aber anbietet, ist nicht immer alle Dateien komplett zu ziehen.  Bei mir sieht das z.B. der Updaten für den aktuellen Tag so aus:
```
GIT_LFS_SKIP_SMUDGE=1 git pull
git lfs smudge < Aktuell_Deutschland_SarsCov2_Infektionen.csv > $DATADIR/data.csv
```

Durch `GIT_LFS_SKIP_SMUDGE=1` werden nur die LFS Referenzen geladen, nicht aber die Dateninhalte selbst.

**Comment by RKIOpenData** [comment]
Issue wird geschlossen (siehe https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv/issues/22#issuecomment-1477501808)
