### ISSUE TITLE
Wie werden Reinfektionen berücksichtigt?

### ISSUE THREAD

**Issue by lucid-dreams** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland#4]
Wann gelten Reinfektionen [1] im Datensatz als neue Fälle?

Hintergrund der Frage ist die aktuelle Häufung von verstorbenen Genesenen in Berlin.

[1] https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Reinfektion.html

**Comment by RKIOpenData** [comment]
Wird geschlossen, Duplikat von https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv/issues/24
