### ISSUE TITLE
Release Datei enthält leeres CSV

### ISSUE THREAD

**Issue by jwildeboer** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland#7]
Wenn man die Release Datei herunterlädt und das tar.gz auspackt, stellt man fest, daß die CSV Datei nur 134 Bytes groß ist und statt der Daten nur drei Zeilen enthält:

version https://git-lfs.github.com/spec/v1
oid sha256:7a88150b4233b0f4fc84a04dab50dc900db04ca9171dbc562f15e0d481a3a859
size 383249659

Ich schätze, daß LFS Dateien bei der Release-Erstellung nicht berücksichtigt werden. Bug oder Feature?

Jan

**Comment by jwildeboer** [comment]
Hängt evtl mit diesem Issue zusammen: https://github.com/o3de/o3de/issues/1919

TL;DR LFS Dateien, die extern gehostet werden, gehen nicht in das Release Package.

**Comment by HannesWuensche** [comment]
Hallo @jwildeboer,

vielen Dank für den Hinweis. Das ist bisher noch niemandem aufgefallen. 

"Response from GitHub Support is that only LFS files from the GitHub application are supported."
Es scheint also die Möglichkeit zu geben. Wir werden uns das mal die Tage anschauen. 

Wenn es um die Reduktion des Download Volumens geht, hätten wir auch noch das `.xz` komprimierte Archiv:
https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv/tree/main/Archiv

Beste Grüße
@HannesWuensche 
RKI | Open Data
