### ISSUE TITLE
Keine neuen Falldaten seit 24.08.2023

### ISSUE THREAD

**Issue by MaHi84** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland#8]
Der aktuelle Datensatz vom 25.08.2023 enthält keine neuen Infektionsdaten vom 24.08.2023

**Comment by Soran56** [comment]
Das kann ich bestätigen. Die Daten hier und auch im Archiv ist die selben in Anzahl an Fällen und Todesfällen, wie der gestrige Datensatz (24.08.2023).

**Comment by HannesWuensche** [comment]
Liebe User,

Vielen Dank für den Hinweis. 
Wir arbeiten an einer Problemlösung, können aber noch nicht abschätzen bis wann wir den Fehler behoben haben und bitten daher um etwas Geduld. 

Beste Grüße
@HannesWuensche 
für das Team RKI | Open Data

**Comment by jwildeboer** [comment]
Für Bayern fehlen seit 2 Tagen die Zahlen.

**Comment by jwildeboer** [comment]
Wenn ich mir die Zahlen für München bei SurvNet anschaue, dann steht dort auch als 7 Tage Summe 35. Genau die gleiche Zahl erhalte ich mit den RKI Daten wo die letzten 3 Tage fehlen. Daher vermute ich das der Fehler wohl bei eher bei SurvNet liegt?

SirvNet Suchkriterien: Wochensumme, München, COVID19, 2023:
<img width="475" alt="Screenshot 2023-08-26 at 13 00 03" src="https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland/assets/873028/0830a295-0aaa-4484-bd0c-a6d2b7c28361">

Ergebnis Summe 35 für laufende Woche:
<img width="273" alt="Screenshot 2023-08-26 at 13 00 19" src="https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland/assets/873028/7214f166-5901-465d-91ea-9cd273d45cea">

Auswertung der RKI Daten mit 0 für die letzten 3 Tage - auch 35 als Summe:
<img width="170" alt="Screenshot 2023-08-26 at 12 59 27" src="https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland/assets/873028/17d18dcf-51cb-48c0-8912-9ff93d3f89ce">

**Comment by MaHi84** [comment]
Wird an SurvNet liegen, sonst hätte Hannes das längst gefixt. ;-)

Vielleicht gibt es nach dem Wochenende ja ein kleines Update zum Stand der Dinge.

**Comment by jwildeboer** [comment]
(Eventuell den Titel des Bugs ändern? Nicht "Keine Daten vom" sondern "Keine Daten *seit*"? Sind mittlerweile 4 Tage ohne neu Zahlen, Nachmeldungen oder Korrekturen)

**Comment by jwildeboer** [comment]
4 Tage ohne Zahlen (zumindest für Bayern) - gibt es eine Info ab wann die Zahlen wieder fliessen? Ansonsten sinken bei uns am Dienstag alle Inzidenzen auf 0 ...

**Comment by RKIOpenData** [comment]
Liebe User,

Wir sind weiter an einer Problemlösung dran. Wir hoffen dass wir ab morgen im Laufe des Tages wieder Zahlen liefern können. Ansonsten schicken wir nochmal ein Update.

Beste Grüße
Knut Perseke
für das Team RKI | Open Data

**Comment by jwildeboer** [comment]
Yeah! Es gibt wieder Zahlen! Vielen Dank für eure Arbeit an dem Fix!

**Comment by RKIOpenData** [comment]
Liebe User,

da die Daten jetzt wieder da sind schließe ich das Ticket hier. Falls es noch Probleme geben sollte macht das Ticket gern wieder auf.

viele Grüße
Knut Perseke
für das Team RKI | Open Data

**Comment by HannesWuensche** [comment]
Hallo @Rubber1Duck,

bezüglich der Archivdaten überlegen wir derzeit noch. Die Daten sind aufgrund des SurvNet Fehlers nicht korrekt, aber gleichzeitig das was wir ausgegeben haben. Also historisch korrekt. 

Liebe Grüße
@HannesWuensche 
für das Team | RKI Open Data

**Comment by Rubber1Duck** [comment]
Hallo @HannesWuensche 
vielen Dank für die Informationen.
Ich verstehe die "Zwickmühle", und warte gespannt auf eure Entscheidung nächste Woche. Es würde ja auch noch die Möglichkeit geben die korrigierten Dateien "zusätzlich" zu veröffentlichen.  Weis aber auch natürlich nicht welchen Aufwand Ihr betreiben müsst die Dateien zu generieren.
LG
Peter

**Comment by Soran56** [comment]
Hallo, 
Zumindestens könnte man eine Note im Archiv machen, das erklärt, das die Daten vom 25.08.2023 -28.08.2023, vom 24.08.2023 sind. Das dieser Zeitraum dann am 29.08.2023 geliefert wurde. 
Sonst geht dieses Wissen verloren, das diese Datensätze duplikate sind.

Gruß
  Hartmut
