### ISSUE TITLE
Fehlende bzw teilweise Updates seit 2023-10-13

### ISSUE THREAD

**Issue by MaHi84** [robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland#9]
Kein neuer Datensatz am 14.10.2023 (und auch folgend), mit den Daten vom 13.10.2023.

Der Archivdatensatz wurde hingegen aktualisiert.

Zendo zuletzt am 11.10.2020.

**Comment by sebkur** [comment]
Würde mich auch über eine Nachricht freuen, ob geplant ist, dieses Repository in der Zukunft weiter zu pflegen oder ob Nutzer auf das Archiv-Repository umsteigen sollten?

**Comment by HannesWuensche** [comment]
Liebe User, 

Teil unseres Veröffentlichungsprozesses ist die Publikation der Daten auf Zenodo.org. Zenodo hat am Freitag eine Systemupdate vorgenommen und in diesem Zuge auch sein API angepasst. 
In der [Dokumentation](https://help.zenodo.org/docs/about/whats-changed/) war diese Änderung nicht aufgeführt, sodass wir vorab nicht davon ausgegangen sind, Anpassungen in unserem Prozess vornehmem zu müssen. Leider kam es am Wochenende dann zu einem Ausfall unseres Prozesses, da die Zenodo API sich nicht wie gewohnt verhalten hat. 

Wir nehmen derzeit die Anpassung vor und hoffen im Verlauf des Tages alle Daten bereitstellen zu können. 

Beste Grüße
@hanneswuensche
für das Team RKI | Open Data

**Comment by sebkur** [comment]
Vielen Dank für die Nachricht!

**Comment by HannesWuensche** [comment]
Im Archiv sind die Daten vorhanden, 
da der Prozess ohne Zenodo läuft.

https://github.com/robert-koch-institut/SARS-CoV-2-Infektionen_in_Deutschland_Archiv
